#!/bin/bash

# Generates iosApp/Configuration/Config.xcconfig from the root .env file.
# SECURITY: only the allowlisted keys below are written. Paid AI provider keys never
# reach the iOS app; all inference goes through the Supabase Edge Function gateway.

ENV_FILE="../.env"
CONFIG_FILE="Configuration/Config.xcconfig"

ALLOWED_KEYS=("GATEWAY_URL" "SUPABASE_URL" "SUPABASE_ANON_KEY" "GOOGLE_ADS_APP_ID")

# "//" starts a comment in .xcconfig files, which would cut "https://host" down to
# "https:". "/$()/" is the standard escape: Xcode expands $() to an empty string.
escape_xcconfig() {
    printf '%s' "$1" | sed 's#//#/$()/#g'
}

if [ ! -f "$ENV_FILE" ]; then
    echo "Warning: .env file not found at $ENV_FILE. Leaving $CONFIG_FILE unchanged."
    exit 0
fi

previous_ads_id=""
if [ -f "$CONFIG_FILE" ]; then
    previous_ads_id=$(grep '^GOOGLE_ADS_APP_ID=' "$CONFIG_FILE" | head -1)
fi

{
    echo "// Generated by generate_config.sh from the root .env file. Do not commit."
    echo "TEAM_ID="
    echo "BUNDLE_ID=com.fitcal.app"
    echo "APP_NAME=FitCal"
} > "$CONFIG_FILE"

wrote_ads_id=false
while IFS= read -r line || [ -n "$line" ]; do
    line=$(echo "$line" | tr -d '\r' | xargs)
    if [[ "$line" =~ ^# ]] || [[ ! "$line" =~ = ]]; then
        continue
    fi
    key="${line%%=*}"
    value="${line#*=}"
    for allowed in "${ALLOWED_KEYS[@]}"; do
        if [ "$key" = "$allowed" ]; then
            echo "$key=$(escape_xcconfig "$value")" >> "$CONFIG_FILE"
            [ "$key" = "GOOGLE_ADS_APP_ID" ] && wrote_ads_id=true
            break
        fi
    done
done < "$ENV_FILE"
echo "Config.xcconfig updated (allowlist: ${ALLOWED_KEYS[*]})."

if [ "$wrote_ads_id" = false ] && [ -n "$previous_ads_id" ]; then
    echo "$previous_ads_id" >> "$CONFIG_FILE"
fi
