# sync_env.ps1
# Windows counterpart of generate_config.sh: writes iosApp/Configuration/Config.xcconfig
# from the root .env file. Only allowlisted keys are written; paid AI provider keys never
# reach the iOS app.

$envFile = "../.env"
$configFile = "Configuration/Config.xcconfig"
$allowedKeys = @("GATEWAY_URL", "SUPABASE_URL", "SUPABASE_ANON_KEY", "GOOGLE_ADS_APP_ID")

# "//" starts a comment in .xcconfig files; "/$()/" keeps URLs intact.
function Escape-XcconfigValue([string]$value) { return $value.Replace('//', '/$()/') }

if (-not (Test-Path $envFile)) {
    Write-Warning ".env file not found at $envFile. Leaving $configFile unchanged."
    return
}

$previousAdsId = $null
if (Test-Path $configFile) {
    $previousAdsId = Get-Content $configFile | Where-Object { $_ -like 'GOOGLE_ADS_APP_ID=*' } | Select-Object -First 1
}

$lines = @(
    "// Generated by sync_env.ps1 from the root .env file. Do not commit.",
    "TEAM_ID=",
    "BUNDLE_ID=com.fitcal.app",
    "APP_NAME=FitCal"
)

$wroteAdsId = $false
foreach ($line in Get-Content $envFile) {
    $trimmed = $line.Trim()
    if ($trimmed -and -not $trimmed.StartsWith('#') -and $trimmed.Contains('=')) {
        $key = $trimmed.Substring(0, $trimmed.IndexOf('='))
        $value = $trimmed.Substring($trimmed.IndexOf('=') + 1)
        if ($allowedKeys -contains $key) {
            $lines += "$key=$(Escape-XcconfigValue $value)"
            if ($key -eq 'GOOGLE_ADS_APP_ID') { $wroteAdsId = $true }
        }
    }
}
Write-Host "Config.xcconfig updated (allowlist: $($allowedKeys -join ', '))."

if (-not $wroteAdsId -and $previousAdsId) { $lines += $previousAdsId }
$lines | Out-File -FilePath $configFile -Encoding ascii
